# Generated by Django 4.1 on 2022-09-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={},
        ),
        migrations.AlterModelTable(
            name='info',
            table=None,
        ),
    ]
