# Generated by Django 4.1 on 2022-08-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_aplly'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplly',
            new_name='Apply',
        ),
    ]
